name: utube_flutter
description: YouTube Android Clone recreated in Flutter (Splash + Home feed).
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  wakelock_plus: ^1.2.10
  material_symbols_icons: ^4.2906.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/en.json
    - assets/i18n/ru.json
    - assets/i18n/kk.json

